services:
  - type: web
    name: n8n
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "./start.sh"
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: N8N_PROTOCOL
        value: https
      - key: EXECUTIONS_MODE
        value: regular
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: fcb
      - key: N8N_BASIC_AUTH_PASSWORD
        value: pavansp
